Traceback (most recent call last):
  File "C:\anaconda3\envs\abe_website\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "C:\anaconda3\envs\abe_website\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\anaconda3\envs\abe_website\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\anaconda3\envs\abe_website\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\anaconda3\envs\abe_website\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\anaconda3\envs\abe_website\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\anaconda3\envs\abe_website\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\anaconda3\envs\abe_website\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from osgeo import gdal

dataset = gdal.Open("path/image.tif")
width = dataset.RasterXSize
height = dataset.RasterYSize
projection = dataset.GetProjection()
geotransform = dataset.GetGeoTransform()
band = dataset.GetRasterBand(1)  # Access the first band (bands are 1-based)
data = band.ReadAsArray()
dataset = None  # Close the dataset

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_14368\2429641457.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0mosgeo[0m [1;32mimport[0m [0mgdal[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [0mdataset[0m [1;33m=[0m [0mgdal[0m[1;33m.[0m[0mOpen[0m[1;33m([0m[1;34m"path/image.tif"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mwidth[0m [1;33m=[0m [0mdataset[0m[1;33m.[0m[0mRasterXSize[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mheight[0m [1;33m=[0m [0mdataset[0m[1;33m.[0m[0mRasterYSize[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'osgeo'
ModuleNotFoundError: No module named 'osgeo'

